name: Bump Pre Release Version

on:
  push:
    branches:
      - dev

jobs:
  bump:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python --version
          python -m pip install commitizen

      - name: Create bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cz bump --yes -pr rc --tag_format="v$minor.$major.$patch-$prerelease"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          branch: dev
          tags: "true"
